[package]
name = "netdog"
version = "1.2.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
lua-src = "547.0.0"
mlua = { version = "0.10.2", features = ["lua54", "vendored"] }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
